name: CI master to experimental

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build and deploy to test system
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-node@v1
      - name: NPM Install
        run: npm install
      - name: NPM Lint & Test
        run: |
          npm run lint
          npm run test
      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/slidewiki/slidewiki/platform:latest-dev .
      - name: Push Docker image
        run: |
          docker login docker.pkg.github.com -u bwulff -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
          docker push docker.pkg.github.com/slidewiki/slidewiki/platform:latest-dev
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
    
