name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build and deploy to test system
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: copy microservice config
        run: cp configs/microservice.sample.js configs/microservices.js
      - uses: actions/setup-node@v1
      - name: NPM Install
        run: npm install
      - name: NPM Lint
        run: npm run lint
      - name: NPM Test
        run: npm run test
      - name: NPM Build
        run: npm run build:nostart
    
